project:
  name: quickstart-checkpoint-autoscale
  owner: quickstart-eng@amazon.com
  package_lambda: false
  parameters:
    AdminCIDR: 10.0.0.0/16
    AvailabilityZones: $[alfred_getaz_2]
    Certificate: ""
    GatewaysAddresses: 10.0.0.0/16
    GatewaysBlades: 'true'
    GatewaysInstanceType: c5.xlarge
    GatewaysLicense: R80.30-BYOL
    GatewaysMaxSize: "10"
    GatewaysMinSize: "2"
    GatewaysPolicy: Standard
    GatewaySICKey: $[alfred_genpass_8]
    KeyName: $[alfred_getkeypair]
    ManagementLicense: R80.30-BYOL
    NumberOfAZs: "2"
    PrivateSubnetCidrA: 10.0.1.0/24
    PrivateSubnetCidrB: 10.0.3.0/24
    PrivateSubnetCidrC: 10.0.5.0/24
    PrivateSubnetCidrD: 10.0.7.0/24
    Protocol: HTTP
    PublicSubnetCidrA: 10.0.0.0/24
    PublicSubnetCidrB: 10.0.2.0/24
    PublicSubnetCidrC: 10.0.4.0/24
    PublicSubnetCidrD: 10.0.6.0/24
    ServerAMI: ""
    ServersDeploy: "false"
    ServicePort: ""
    VpcCidr: 10.0.0.0/16
    CloudWatch: 'true'
    EnableInstanceConnect: 'false'
    AllowUploadDownload: 'true'
    EnableVolumeEncryption: 'true'
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - eu-west-3
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  s3_bucket: ''
tests:
  checkpoint-alb-mgmt:
    parameters:
      ExternalLoadBalancerType: Application Load Balancer
      ManagementDeploy: "false"
      Tag: TaskCat1
    regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - eu-west-2
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
    s3_bucket: ''
    template: templates/qs-autoscale-main.template.yaml
  checkpoint-nlb-no-mgmt:
    parameters:
      ExternalLoadBalancerType: Network Load Balancer
      ManagementDeploy: "true"
      ManagementInstanceType: "m5.xlarge"
      Tag: TaskCat2
    regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - eu-west-2
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
    s3_bucket: ''
    template: templates/qs-autoscale-main.template.yaml
